### ISSUE TITLE
Re-work database schema to accommodate changes

### ISSUE THREAD

**Issue by Parasrah** [agriculture-capstone/agricore#28]
# Description
Due to some changes in requirements, the schema has to change to support traders owning the same farmers.

# Acceptance Criteria
- Create new database schema to accommodate traders owning either:
  - The same farmers
  - Different farmers

## Reviewer
Moath
Bea

**Comment by jeinglis** [comment]
- I have made farmer a strong entity by dropping the foreign key from trader and making the Id its primary key.
- I realized we didn't have a way to explicitly track payments so I added a pay table
- I also added a possible solution for the addition of a Driver entity.

**Comment by jeinglis** [comment]
Add Milk payout table
and transactions table
 - all money in same place
