### ISSUE TITLE
Professional README

### ISSUE THREAD

**Issue by ExtraGravity** [agriculture-capstone/agricore#7]
The AC README could use a more professional tone and be in third person.

**Comment by Parasrah** [comment]
I'd personally rather avoid overly professional tones in the documentation we leave behind. A more casual tone explains the topic just as well, while conveying a more soothing message to people using this to learn. More professional README's can be pretty intimidating. I think we should be judging a README based on how effectively it can teach someone what it intends to

An example of how we can keep things light hearted is the README I wrote for my initial stab at a vue template [here](https://github.com/agriculture-capstone/dashboard/blob/init/src/README.md)

**Comment by ExtraGravity** [comment]
Although as a whole I disagree and think professional documentation is better in general, I think that attitude is fine for inline code. 

But some of the content in these READMEs could easily be customer facing one day and having a tone like that is not acceptable. It will be easier in the future if we need to rip out of the content to put in customer facing documentation.

Also I think a big indicator of good code, is that it is all consistent. That's hard to do with casual documentation.

**Comment by ExtraGravity** [comment]
Discussed with team to move forward with professional tone.

https://github.com/agriculture-capstone/agriculture-core/pull/14 PR created and assigned Brad.
